server:
  port: 9001
  servlet:
    context-path: /dear-future
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: eduardo.lopes234@gmail.com
    password: uvavcugbrojhbelx
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  jackson:
    default-property-inclusion: non-null
  datasource:
    url: jdbc:mysql://localhost:8889/dear_future
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    open-in-view: false
    
config:
  jwt:
    keystore-location: key-store.jks
    keystore-password: 69465197
    key-alias: keystore
    private-key-passphrase: 69465197